### ISSUE TITLE
Ubuntu 16 support

### ISSUE THREAD

**Issue by vikas5914** [serversetup/SetupServer#1]
this was my college project . initially it was support to have support for both Ubuntu 14 and 16 . but i was not able to add Ubuntu 16 support .. and after i finish my college ,i abandoned this project.

I want to add new thing to this project .. if you could help me . it would be great .

**Comment by srisankethu** [comment]
Hi Vikas, Does your project work on proxy?

**Comment by vikas5914** [comment]
@srisankethu  proxy like reverse proxy feature from nginx ?

**Comment by srisankethu** [comment]
I haven't got any idea on your project right now but i am working under my college proxy.

**Comment by vikas5914** [comment]
@srisankethu yes . it works under college proxy

**Comment by srisankethu** [comment]
Great! I will have a look into it. Give me some input on it :+1:

**Comment by srisankethu** [comment]
sorry! i was kinda fast in taking this up. You used different tools in your project and i am totally new with their API. Its gonna take some time for me to understand and correct the issue. So, i want to opt out. Sorry :(
